name: Build and publish container image
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.0
        with:
          repository: abrt/faf
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
          registry: quay.io
          tag_with_ref: true
          dockerfile: container/Dockerfile
